### ISSUE TITLE
Add more content to get started with Spectacle

### ISSUE THREAD

**Issue by paulathevalley** [FormidableLabs/spectacle-docs#21]
As per discussion with Marketing, the Spectacle docs could benefit from more content. 

Ideas for content: Getting Started Guide, API documentation, FAQ documentation... I’d recommend starting with whichever makes the most sense for the homepage.

I would suggest adding content as markdown files to a `/docs` folder in the [Spectacle](https://github.com/FormidableLabs/spectacle) repo (unless Wheels says otherwise). This follows the convention established by [Radium/docs](https://github.com/FormidableLabs/radium/tree/master/docs).

/cc @kenwheeler @ebrillhart

**Comment by kenwheeler** [comment]
Sounds good to me

**Comment by ebrillhart** [comment]
- [ ] Getting Started Guide
- [ ] API Documentation
- [ ] FAQ stuff (maybe later)
- [ ] About Spectacle

**Comment by paulathevalley** [comment]
Resolved by https://github.com/FormidableLabs/spectacle-docs/pull/26 ! 
(definitely pushing FAQ to later)
