### ISSUE TITLE
Themes docs default theme confusion

### ISSUE THREAD

**Issue by eastridge** [FormidableLabs/spectacle-docs#33]
https://formidable.com/open-source/spectacle/docs/basic-concepts/#themes

The text here describes importing the defaultTheme, but the code example refers to `createTheme`.

<img width="810" alt="screen shot 2016-10-19 at 9 02 57 pm" src="https://cloud.githubusercontent.com/assets/30921/19535409/6e540d22-963f-11e6-84ad-3b1a19882ca1.png">

Additionally if there are other themes available we should list them in the themes section.

**Comment by ebrillhart** [comment]
@eastridge no other themes as of now, but will change that line in the docs. thanks for the heads up!

**Comment by ebrillhart** [comment]
@eastridge and upon looking at it further, it actually is correct as `createTheme`, since it's a function that can be called as-is for the default theme or modified to create a new theme. cc/ @kenwheeler for confirmation of that
