### ISSUE TITLE
Sample decks section

### ISSUE THREAD

**Issue by eastridge** [FormidableLabs/spectacle-docs#34]
Add a "Sample Decks" section with links to the source. Any fully polished decks made by other Formidable's are good, also things with interactive examples or playgrounds.

**Comment by paulathevalley** [comment]
There's an issue in `spectacle` with a list of Presentations built with Spectacle: https://github.com/FormidableLabs/spectacle/issues/134 

Does anyone know of any other lists like that? I’m thinking it might be a good use case to add a wiki page to `spectacle` with this list, so anyone who created a spectacle deck/presentation can edit the wiki page directly. We could curate/filter the list on the website, or link to the wiki page directly (my personal preference).

I know of a few Formidable public presentations: 
https://github.com/FormidableLabs/presentations
https://github.com/FormidableLabs/deck-victory
https://github.com/FormidableLabs/builder-decks

/cc @ebrillhart @kenwheeler thoughts? preferences? ideas?
