### ISSUE TITLE
Anchor links occasionally do not work or the page will flash/blink

### ISSUE THREAD

**Issue by paulathevalley** [FormidableLabs/spectacle-docs#35]
Steps to reproduce (maybe?) the blinking behavior:
1. Start at https://formidable.com/open-source/spectacle/
2. Click on Basic Concepts
3. Click on Main file in the TOC 
The page will navigate to the anchor, then blink to the top of the page, then go back to the anchor. 

Still figuring out steps to reproduce when links occasionally don't work.

**Comment by bmathews** [comment]
What's happening is:

- Your current URL is: `/docs/basic-concepts`, no trailing slash.
- TOC `Main file` URL is `/docs/basic-concepts/#main-file`, with trailing slash.
- You click on it
- Browser scrolls down to #main-file anchor
- Browser begins navigate to the URL with trailing slash
- Browser reloads entire page
- Browser scrolls down to #main-file anchor.

**Comment by paulathevalley** [comment]
Resolved by #37
