### ISSUE TITLE
New lander launch todos

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/spectacle-docs#58]

**Comment by markprescott** [comment]
![screen shot 2019-02-01 at 2 39 27 pm](https://user-images.githubusercontent.com/40902328/52153670-ca3fad80-262f-11e9-93d1-f7af7bc7fc25.png)

proper top-level nav items shown in this screenshot. 
Colors for links can be #895160 in this case, UNLESS you have a way to programmatically take the key color and darken it a few shades, so it's legible on white.
Hover states for links can be black + underline
Also showing the anchor tags with the color applied and line-spacing tightened up from what we saw today
