### ISSUE TITLE
Add a sticky title bar

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/spectacle-docs#61]
Add bar behind spectacle title and formidable logo. Make nav bar sticky

**Comment by markprescott** [comment]
<img width="319" alt="screen shot 2019-02-04 at 10 13 57 am" src="https://user-images.githubusercontent.com/40902328/52227897-b2ea0580-2865-11e9-91cf-e42c3bab95b2.png">
<img width="583" alt="screen shot 2019-02-04 at 10 13 28 am" src="https://user-images.githubusercontent.com/40902328/52227898-b2ea0580-2865-11e9-9e06-ade7b8387948.png">
<img width="758" alt="screen shot 2019-02-04 at 10 13 06 am" src="https://user-images.githubusercontent.com/40902328/52227899-b2ea0580-2865-11e9-9abe-6ae29dee7777.png">

This is what it looks like on each screen size. White, 54px tall, slight drop shadow.
