### ISSUE TITLE
Improve front page spectacle demo

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/spectacle-docs#75]
The current demo is a video from the old lander. 

It would be awesome to use a live demo on the front page instead of a video.

If we want to keep using a video, it could be updated so that the content is more up to date and so that the color matches the new lander colors better.

**Comment by kale-stew** [comment]
Taking care of this in the v6 rewrite. Check it out in the [main repo](https://github.com/FormidableLabs/spectacle). 🙂
