### ISSUE TITLE
Mobile placement of hero badge

### ISSUE THREAD

**Issue by jevakallio** [FormidableLabs/spectacle-docs#88]
On narrow breakpoints, the hero badge svg is misaligned.

<img width="354" alt="Screen Shot 2019-05-21 at 15 20 42" src="https://user-images.githubusercontent.com/1203949/58104385-a1dabf80-7bdc-11e9-858f-10661c846c18.png">

**Comment by jevakallio** [comment]
Dominic's got this fixed on urql-docs, he'll patch the fix to spectacle-docs as well.

**Comment by kale-stew** [comment]
Will re-open this issue against the new source in the main repo if it persists. 🙂
